# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hdz_grpc_msg/hdz_grpc_msg.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fhdz_grpc_msg/hdz_grpc_msg.proto\x12\x0chdz_grpc_msg\x1a\x1bgoogle/protobuf/empty.proto\"V\n\x11SetGripperRequest\x12\x13\n\x0bgrasp_depth\x18\x01 \x01(\x01\x12\x18\n\x10normalized_width\x18\x02 \x01(\x01\x12\x12\n\nmax_effort\x18\x03 \x01(\x01\"\x15\n\x05\x41rray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\".\n\x0b\x42oolWithMsg\x12\x12\n\nis_success\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x15\n\x06StrMsg\x12\x0b\n\x03str\x18\x01 \x01(\t\"C\n\x0bPoseStamped\x12\x12\n\nframe_name\x18\x01 \x01(\t\x12 \n\x04pose\x18\x02 \x01(\x0b\x32\x12.hdz_grpc_msg.Pose\"\\\n\x04Pose\x12%\n\x08position\x18\x01 \x01(\x0b\x32\x13.hdz_grpc_msg.Point\x12-\n\x0borientation\x18\x02 \x01(\x0b\x32\x18.hdz_grpc_msg.Quaternion\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\x32\x41\n\x07Greeter\x12\x36\n\x08SayHello\x12\x14.hdz_grpc_msg.StrMsg\x1a\x14.hdz_grpc_msg.StrMsg2\x93\x03\n\x03\x41rm\x12>\n\x06MoveTo\x12\x19.hdz_grpc_msg.PoseStamped\x1a\x19.hdz_grpc_msg.BoolWithMsg\x12\x45\n\x13MoveToJointPosition\x12\x13.hdz_grpc_msg.Array\x1a\x19.hdz_grpc_msg.BoolWithMsg\x12>\n\x0bMoveToNamed\x12\x14.hdz_grpc_msg.StrMsg\x1a\x19.hdz_grpc_msg.BoolWithMsg\x12H\n\nSetGripper\x12\x1f.hdz_grpc_msg.SetGripperRequest\x1a\x19.hdz_grpc_msg.BoolWithMsg\x12:\n\x07GetPose\x12\x14.hdz_grpc_msg.StrMsg\x1a\x19.hdz_grpc_msg.PoseStamped\x12?\n\x10GetJointPosition\x12\x16.google.protobuf.Empty\x1a\x13.hdz_grpc_msg.Arrayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hdz_grpc_msg.hdz_grpc_msg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETGRIPPERREQUEST']._serialized_start=78
  _globals['_SETGRIPPERREQUEST']._serialized_end=164
  _globals['_ARRAY']._serialized_start=166
  _globals['_ARRAY']._serialized_end=187
  _globals['_BOOLWITHMSG']._serialized_start=189
  _globals['_BOOLWITHMSG']._serialized_end=235
  _globals['_STRMSG']._serialized_start=237
  _globals['_STRMSG']._serialized_end=258
  _globals['_POSESTAMPED']._serialized_start=260
  _globals['_POSESTAMPED']._serialized_end=327
  _globals['_POSE']._serialized_start=329
  _globals['_POSE']._serialized_end=421
  _globals['_POINT']._serialized_start=423
  _globals['_POINT']._serialized_end=463
  _globals['_QUATERNION']._serialized_start=465
  _globals['_QUATERNION']._serialized_end=521
  _globals['_GREETER']._serialized_start=523
  _globals['_GREETER']._serialized_end=588
  _globals['_ARM']._serialized_start=591
  _globals['_ARM']._serialized_end=994
# @@protoc_insertion_point(module_scope)
