# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grasp_model_grpc_msg import grasp_model_grpc_msg_pb2 as grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2


class GreeterStub(object):
    """Service definition.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/grasp_model_grpc_msg.Greeter/SayHello',
                request_serializer=grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.StrMsg.SerializeToString,
                response_deserializer=grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.StrMsg.FromString,
                )


class GreeterServicer(object):
    """Service definition.

    """

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.StrMsg.FromString,
                    response_serializer=grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.StrMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grasp_model_grpc_msg.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Service definition.

    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grasp_model_grpc_msg.Greeter/SayHello',
            grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.StrMsg.SerializeToString,
            grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.StrMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class GraspModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateFromPointCloud = channel.unary_unary(
                '/grasp_model_grpc_msg.GraspModel/GenerateFromPointCloud',
                request_serializer=grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.PointCloud.SerializeToString,
                response_deserializer=grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.PoseStamped.FromString,
                )


class GraspModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateFromPointCloud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraspModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateFromPointCloud': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFromPointCloud,
                    request_deserializer=grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.PointCloud.FromString,
                    response_serializer=grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.PoseStamped.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grasp_model_grpc_msg.GraspModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GraspModel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateFromPointCloud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grasp_model_grpc_msg.GraspModel/GenerateFromPointCloud',
            grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.PointCloud.SerializeToString,
            grasp__model__grpc__msg_dot_grasp__model__grpc__msg__pb2.PoseStamped.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
